name: vialticecmr
description: "Gestion Transport."
publish_to: 'none'
version: 1.0.14

environment:
  sdk: '>=3.2.0-60.0.dev <4.0.0'

dependencies:
  cron: ^0.5.1
  crypto: ^3.0.3
  cunning_document_scanner: ^1.1.2
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.1
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.3.1
  geolocator: ^9.0.2
  hand_signature: ^3.0.1
  image: ^4.0.17
  images_picker: ^1.2.11
  json_theme: ^6.2.2
  package_info_plus: ^4.1.0
  page_transition: ^2.0.9
  path_provider: ^2.1.0
  scan: ^1.6.0
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
      - assets/img_logo_ecmr.png
      - assets/appainter_theme_jaune.json
      - assets/plaque.png
