// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmrM5a36XPbJoR__OY-ukn60RLhgIlQEA',
    appId: '1:584162305733:web:89fce6d102a86e2437b2ac',
    messagingSenderId: '584162305733',
    projectId: 'vialtic-ecmr',
    authDomain: 'vialtic-ecmr.firebaseapp.com',
    storageBucket: 'vialtic-ecmr.appspot.com',
    measurementId: 'G-PTWNXXK5WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnH6SjepFlROh_g_EU2SBuPwv_7OK9WOg',
    appId: '1:584162305733:android:d1c622c0425b319c37b2ac',
    messagingSenderId: '584162305733',
    projectId: 'vialtic-ecmr',
    storageBucket: 'vialtic-ecmr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_FHJQSO7yWZpeM5ZyehTm4wZQ3e10EKE',
    appId: '1:584162305733:ios:4cec0b95ccfeac5637b2ac',
    messagingSenderId: '584162305733',
    projectId: 'vialtic-ecmr',
    storageBucket: 'vialtic-ecmr.appspot.com',
    iosClientId: '584162305733-79cbojuqss1c3v8bcne8ta361imd8a3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.vialticecmr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_FHJQSO7yWZpeM5ZyehTm4wZQ3e10EKE',
    appId: '1:584162305733:ios:ea543f6451c80e1637b2ac',
    messagingSenderId: '584162305733',
    projectId: 'vialtic-ecmr',
    storageBucket: 'vialtic-ecmr.appspot.com',
    iosClientId: '584162305733-eoikld42je3s80loa4meqg8ukgphis0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.vialticecmr.RunnerTests',
  );
}
